#+TITLE: Emacs API Clients for GitHub & GitLab
#+AUTHOR: Toby Slight
#+STARTUP: showall
* Overview

  A way to batch run Git operations on all local or just specific forge
  repositories.

  You can clone or pull all repositories in one fail swoop with
  ~lazygithub-clone-or-pull-all~ or ~lazygitlab-clone-or-pull-all~.

  You can interactively choose a single repository from any available to you on
  a forge with either ~lazygitlab-clone-or-pull-project~ or
  ~lazygithub-clone-or-pull-repo~.

  For GitLab you can also clone or pull all the repositories under a given
  group with ~lazygitlab-clone-or-pull-group~.

  ~lazygit-pull-all~ will search for all the git repos under ~$HOME~ on your
  system and run ~git pull~ on them.

  ~lazygit-status-all~ will do the same but running ~git status~.

  The results of all operations will appear in a new buffer with links to the
  repos that have been updated or have uncommitted changes.

  ~lazygitlab-retriever~ and ~lazygithub-retriever~ allow arbitrary querying of
  endpoints. You can view the JSON results pretty printed in a dedicated buffer.

* Authentication

  You will be asked to enter your /Personal Access Token/ the first time you run
  a command.

  Generate a *GitHub* /Personal Access Token/ [[https://github.com/settings/tokens][here]].

  Generate a *GitLab* /Personal Access Token/ [[https://gitlab.com/profile/personal_access_tokens][here]].

  I'm using ~auth-source~ to retrieve and store this token in ~$HOME/.authinfo~
  or ~$HOME/.authinfo.gpg~.

* Configuration

  To batch pull and view status locally

  #+begin_src emacs-lisp
    (require 'lazygit)
    (global-set-key (kbd "C-c g h r") 'lazygit-status-all)
    (global-set-key (kbd "C-c g h a") 'lazygit-pull-all)
  #+end_src

  If you want GitHub access:

  #+begin_src emacs-lisp
    (require 'lazygithub)
    (setq lazygithub-directory (expand-file-name "~/github"))
    (global-set-key (kbd "C-c g h r") 'lazygithub-clone-or-pull-repo)
    (global-set-key (kbd "C-c g h a") 'lazygithub-clone-or-pull-all)
  #+end_src

  If you want GitLab access:

  #+begin_src emacs-lisp
    (require 'lazygitlab)
    (setq lazygithub-directory (expand-file-name "~/gitlab"))
    (global-set-key (kbd "C-c g l p") 'lazygitlab-clone-or-pull-project)
    (global-set-key (kbd "C-c g l g") 'lazygitlab-clone-or-pull-group)
    (global-set-key (kbd "C-c g l a") 'lazygitlab-clone-or-pull-all)
  #+end_src

** Use Package

   #+begin_src emacs-lisp
     (use-package lazygit :load-path "/path/to/cloned/repo"
       :bind
       ("C-c g s" . lazygit-status-all)
       ("C-c g p" . lazygit-pull-all))
   #+end_src

   #+begin_src emacs-lisp
     (use-package lazygitlab
       :after lazygit
       :bind
       ("C-c g l a" . lazygitlab-clone-or-pull-all)
       ("C-c g l p" . lazygitlab-clone-or-pull-project)
       ("C-c g l g" . lazygitlab-clone-or-pull-group)
       :config
       (setq lazygitlab-directory (expand-file-name "/gitlab/projects/destination"))
   #+end_src

   #+begin_src emacs-lisp
     (use-package lazygithub
       :after lazygit
       :bind
       ("C-c g h a" . lazygithub-clone-or-pull-all)
       ("C-c g h r" . lazygithub-clone-or-pull-repo)
       :config
       (setq lazygithub-directory (expand-file-name "/github/projects/destination"))
   #+end_src
