* Emacs API Clients for GitHub & GitLab

** Overview

So far I have implemented functions to clone or pull repositories from a list
of repositories available to the authenticated user, with
~lazygitlab-clone-or-pull-repo~ or ~lazygithub-clone-or-pull-repo~.

You can clone or pull all repositories in one fail swoop with
~lazygithub-clone-or-pull-all~ or ~lazygitlab-clone-or-pull-all~.

For GitLab you can also clone or pull all the repositories under a given group
with ~lazygitlab-clone-or-pull-group~.

~lazygitlab-retriever~ and ~lazygithub-retriever~ allow arbitrary querying of
endpoints. You can view the JSON results pretty printed in a dedicated buffer.

~lazygit-pull-all~ will search for all the git repos under ~$HOME~ on your
system and run ~git pull~ on them. ~lazygit-status-all~ will do the same but
running ~git status~. The results will appear in a new buffer with links to the
repos that have been updated or have uncommitted changes.

*N.B.* /I have only tested this on Emacs 27 & 28... Feedback running on other
versions greatly appreciated/

** Authentication

You will be asked to enter your /Personal Access Token/ the first time you run
a command.

Generate a *GitHub* /Personal Access Token/ [[https://github.com/settings/tokens][here]].

Generate a *GitLab* /Personal Access Token/ [[https://gitlab.com/profile/personal_access_tokens][here]].

I'm using ~auth-source~ to retrieve and store this token in ~$HOME/.authinfo~
or ~$HOME/.authinfo.gpg~.

** Configuration

If you want GitHub access:

#+begin_src emacs-lisp
  (add-to-list 'load-path (expand-file-name "~/src/gitlab/tspub/lisp/lazygit"))

  (with-eval-after-load 'lazygithub
    (setq lazygit-directory (expand-file-name "~/src/github"))
    (message "Lazy loaded lazygithub :-)"))

  (autoload 'lazygithub-clone-or-pull-repo "lazygithub" nil t)
  (global-set-key (kbd "C-c g h r") 'lazygithub-clone-or-pull-repo)
#+end_src

If you want GitLab access:

#+begin_src emacs-lisp
  (add-to-list 'load-path (expand-file-name "~/src/gitlab/tspub/lisp/lazygit"))

  (with-eval-after-load 'lazygitlab
    (setq lazygit-directory (expand-file-name "~/src/gitlab"))
    (message "Lazy loaded lazygitlab :-)"))

  (autoload 'lazygitlab-clone-or-pull-project "lazygitlab" nil t)
  (global-set-key (kbd "C-c g l p") 'lazygitlab-clone-or-pull-project)
#+end_src

*** Use Package

#+begin_src emacs-lisp
  (use-package lazygit
               :load-path "/path/to/cloned/repo")

  (use-package lazygitlab
               :after lazygit
               :bind
               ("C-c g l a" . lazygitlab-clone-or-pull-all)
               ("C-c g l c" . lazygitlab-clone-or-pull-project)
               ("C-c g l g" . lazygitlab-clone-or-pull-group)
               ("C-c g l r" . lazygitlab-retriever)
               :config
               (defalias 'gl/api 'lazygitlab-retriever)
               (defalias 'gl/all 'lazygitlab-clone-or-pull-all)
               (defalias 'gl/grp 'lazygitlab-clone-or-pull-group)
               (defalias 'gl/repo 'lazygitlab-clone-or-pull-project))

  (use-package lazygithub
               :after lazygit
               :bind
               ("C-c g h a" . lazygithub-clone-or-pull-all)
               ("C-c g h c" . lazygithub-clone-or-pull-repo)
               ("C-c g h r" . lazygithub-retriever)
               :config
               (defalias 'gh/api 'lazygithub-retriever)
               (defalias 'gh/all 'lazygithub-clone-or-pull-all)
               (defalias 'gh/repo 'lazygithub-clone-or-pull-repo))
#+end_src
