#+TITLE: Emacs API Clients for GitHub & GitLab
#+AUTHOR: Toby Slight
#+STARTUP: showall

* Overview

  A way to batch run Git operations on all local or just specific forge
  repositories.

  You can clone or pull all repositories in one fail swoop with
  ~lazygithub-clone-or-pull-all~ or ~lazygitlab-clone-or-pull-all~.

  You can interactively choose a single repository from any available to you on
  a forge with either ~lazygitlab-clone-or-pull-project~ or
  ~lazygithub-clone-or-pull-repo~.

  For GitLab you can also clone or pull all the repositories under a given
  group with ~lazygitlab-clone-or-pull-group~.

  ~lazygit-pull-all~ will search for all the git repos under ~$HOME~ on your
  system and run ~git pull~ on them.

  ~lazygit-status-all~ will do the same but running ~git status~.

  The results of all operations will appear in a new buffer with links to the
  repos that have been updated or have uncommitted changes.

  ~lazygitlab-retriever~ and ~lazygithub-retriever~ allow arbitrary querying of
  endpoints. You can view the JSON results pretty printed in a dedicated buffer.

* Authentication

  You will be asked to enter your /Personal Access Token/ the first time you run
  a command.

  Generate a *GitHub* /Personal Access Token/ [[https://github.com/settings/tokens][here]].

  Generate a *GitLab* /Personal Access Token/ [[https://gitlab.com/profile/personal_access_tokens][here]].

  I'm using ~auth-source~ to retrieve and store this token in ~$HOME/.authinfo~
  or ~$HOME/.authinfo.gpg~.

* Configuration

  #+begin_src emacs-lisp
    (use-package lazygit :ensure nil
      :load-path "~/src/gitlab/tspub/lisp/lazygit"
      :bind-keymap
      ("C-c g" . lazygit-map)
      :config
      (setq lazygit-directory "~/src"))

    (use-package lazygitlab :ensure nil
      :requires lazygit
      :bind-keymap
      ("C-c l" . lazygitlab-map)
      (setq lazygitlab-directory "~/src/gitlab"))

    (use-package lazygithub :ensure nil
      :requires lazygit
      :bind-keymap
      ("C-c h" . lazygithub-map)
      (setq lazygitlab-directory "~/src/github"))
  #+end_src
